export const origin='https://subair71.github.io';
export const basePath='/samia-bourimech-immobilier';
export type Lang='fr'|'en';
export const paths:Record<string,[string,string]>={home:['',''],buy:['acheter','buy'],sell:['vendre','sell'],valuation:['estimation-immobiliere-villepinte','property-valuation-villepinte'],properties:['biens','properties'],areas:['secteurs','areas'],about:['a-propos','about'],insights:['conseils','insights'],contact:['contact','contact'],reviews:['avis-clients','testimonials'],local:['immobilier-villepinte','real-estate-villepinte'],privacy:['confidentialite','privacy'],legal:['mentions-legales','legal-notice'],prepare:['conseils/preparer-son-bien','insights/preparing-your-property'],valueguide:['conseils/estimer-a-villepinte','insights/understanding-property-value'],buyguide:['conseils/acheter-a-villepinte','insights/buying-near-paris'],house:['biens/maison-exemple','properties/example-house'],apartment:['biens/appartement-exemple','properties/example-apartment'],loft:['biens/loft-exemple','properties/example-loft']};
export const url=(l:Lang,k:string)=>`${basePath}/${l}/${paths[k][l==='fr'?0:1]}${k==='home'?'':'/'}`;
export const labels:Record<string,[string,string]>={home:['Accueil','Home'],buy:['Acheter','Buy'],sell:['Vendre','Sell'],valuation:['Estimation','Property Valuation'],properties:['Biens','Properties'],areas:['Secteurs','Areas'],about:['À propos','About'],insights:['Conseils','Insights'],contact:['Contact','Contact'],reviews:['Avis clients','Testimonials'],local:['Immobilier à Villepinte','Villepinte Real Estate'],privacy:['Confidentialité','Privacy'],legal:['Mentions légales','Legal Notice'],prepare:['Préparer son bien pour la vente','Preparing Your Home for Sale'],valueguide:['Comprendre la valeur de son bien','Understanding Your Property’s Value'],buyguide:['Acheter à Villepinte : définir son projet','Buying Near Paris: Define Your Priorities'],house:['Une maison ouverte sur le jardin','A Home Opening onto the Garden'],apartment:['La lumière pour signature','A Home Defined by Light'],loft:['Un nouvel art de vivre','A Fresh Perspective on Home']};
export const tr=(l:Lang,fr:string,en:string)=>l==='fr'?fr:en;
export const label=(l:Lang,k:string)=>labels[k]?.[l==='fr'?0:1]||k;
export const properties=[{key:'house',type:'house',image:'house',price:425000,area:112,rooms:5,beds:3},{key:'apartment',type:'apartment',image:'apartment',price:249000,area:68,rooms:3,beds:2},{key:'loft',type:'apartment',image:'hero',price:315000,area:86,rooms:4,beds:3}];
